development:
  adapter: postgresql
  encoding: unicode
  database: heroku_db
  pool: 5
  username: local
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: local
  password: 1234
